<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://main.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="interface1Service" targetNamespace="http://main.com/">
<wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://main.com/" elementFormDefault="unqualified" targetNamespace="http://main.com/" version="1.0">
<xs:element name="dispaly" type="tns:dispaly"/>
<xs:element name="dispalyResponse" type="tns:dispalyResponse"/>
<xs:complexType name="dispaly">
<xs:sequence>
<xs:element name="arg0" type="xs:int"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="dispalyResponse">
<xs:sequence>
<xs:element name="return" type="xs:int"/>
</xs:sequence>
</xs:complexType>
</xs:schema>
</wsdl:types>
<wsdl:message name="dispaly">
<wsdl:part element="tns:dispaly" name="parameters"></wsdl:part>
</wsdl:message>
<wsdl:message name="dispalyResponse">
<wsdl:part element="tns:dispalyResponse" name="parameters"></wsdl:part>
</wsdl:message>
<wsdl:portType name="interface1">
<wsdl:operation name="dispaly">
<wsdl:input message="tns:dispaly" name="dispaly"></wsdl:input>
<wsdl:output message="tns:dispalyResponse" name="dispalyResponse"></wsdl:output>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="interface1ServiceSoapBinding" type="tns:interface1">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="dispaly">
<soap:operation soapAction="" style="document"/>
<wsdl:input name="dispaly">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="dispalyResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="interface1Service">
<wsdl:port binding="tns:interface1ServiceSoapBinding" name="interface1Port">
<soap:address location="http://localhost:8081/dis"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>